### ISSUE TITLE
Modify the request timeout

### ISSUE THREAD

**Issue by rainbowdashlabs** [TristanBrotherton/netcheck#17]
Thanks for this awesome tool.

I have to deal with often quite short connection problems which are in general enough to kill real time applications like voip or online games.

Sadly most of these interruptions are quite short and are only recognized in very rare cases by netcheck. (Nearly 20 disconnects only 2 are actually logged.) 
Would it be possible to modify the tool to allow a shorter timeout of the request or maybe make it more sensitive in general?
If I see it right its currently hardcoded to 10 seconds, but imo a website especially google should always respond in 3 or less seconds.

**Comment by TristanBrotherton** [comment]
Hi there, 

Thanks for the kind words - This option is already available. The default interval is 5 seconds but you can customise it using the -c option. Further details are in the readme file.

**Comment by rainbowdashlabs** [comment]
So the -c option defines the interval and the request timeout seconds as well? Thanks for the clarification.

**Comment by smeech** [comment]
A related query so I hope you'll forgive me if I extend this old thread - if not I'll start a new one.

I have the opposite problem in that I am happy to ignore short (or possibly spurious) outages that generate  “TOTAL DOWNTIME:   0 minutes and 5 seconds.” which don't appear to trigger a modem reconnection process, and aren't consistent between two machines running Netcheck simultaneously, in favour of those that last several minutes and actually affect our usage.

Would a `netcheck.sh -c` setting help me too? `-c 10` will just result in less frequent checking rather than ignoring a short break, AFAICS?
